#!/bin/bash -e

alias enter_container="docker exec -it \$(docker ps -n 1 -q) /bin/bash"
alias remove_dangling_images='docker images -q --filter=dangling=true | xargs docker rmi -f'
alias remove_containers='docker ps -aq | xargs docker rm -f'
alias d='docker'

function d-run() {
  local curdir=$(pwd)
  local image=${1:-ubuntu}
  shift
  command=( "$@" )
  if [ -z "$1" ]; then
    command="bash"
  fi
  docker run \
    -it \
    -w $curdir \
    -v $curdir:$curdir \
    -v /tmp:/tmp \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -e HOME=$curdir \
    $image \
    $command
}
