#!/bin/bash -e

function dotfiles_save() {
  (
    cd $DOTFILES_DIR &&
    (git diff --stat | cat) &&
    git add -A . &&
    git commit -am"saving dotfiles as of $(date +"%d/%m/%Y")" &&
    git push origin
  )
}

function dotfiles_load() {
  (source $DOTFILES_DIR/.bashrc)
}

function dotfiles_pull() {
  (
    cd $DOTFILES_DIR &&
    git stash -u &&
    git pull --rebase origin master &&
    g stash pop
  )
}
