#!/bin/bash -e

function bootstrap_git() {
  git config --global pull.rebase true
  git config --global alias.co checkout
  git config --global alias.st status
  git config --global alias.pup '!git push --set-upstream origin `git rev-parse --abbrev-ref HEAD`'
  git config --global alias.cleanup '!git fetch --prune && git branch -d $(git branch --merged | tail +2)'

  git config --global push.default simple

  # global gitignore
  git config --global core.excludesfile $DOTFILES_DIR/.gitignore_global

  # turn of advices
  git config --global advice.pushnonfastforward false
  git config --global advice.statushints false
  git config --global advice.commitbeforemerge false
  git config --global advice.resolveconflict false
  git config --global advice.implicitidentity false
  git config --global advice.detachedhead false

  # gpg setup
  if [[ -x "$(which gpg)" ]]; then
    git config --global gpg.program "$(which gpg)"
  fi
}

alias g='git'
alias gdiff='git diff --no-index -- '

alias clean_wd="git clean -dfnx | grep -v .idea | sed 's/Would remove //' | xargs rm -rfv"
