#!/bin/bash -e

export PATH=$HOME/bin:/usr/local/bin:$PATH

if [ -d "/opt/homebrew/bin/brew" ]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

export HISTFILESIZE=1000000000
export HISTSIZE=1000000000

setopt HIST_FIND_NO_DUPS
setopt INC_APPEND_HISTORY

alias less="less -N"
alias ls='ls -G --color'

export LC_ALL=en_US.UTF-8

alias getp='ps axu | grep -v grep | grep -i '

alias speedtest='wget -O /dev/null http://speedtest.wdc01.softlayer.com/downloads/test100.zip'
alias ip='ifconfig | grep -e '\''inet [0-9]'\'' | grep -ve '\''inet 127'\'' | awk -F '\'' '\'' '\''{print $2; }'\'' | tr -d '\''\n'\'''
alias fastping='prettyping --nounicode -i 0.1'

function timestamp() {
  date -j -f '%Y-%m-%d %H:%M:%S' "$1" +%s
}

function install_prettyping() {
	(mkdir -p ~/bin && cd ~/bin && curl -O https://raw.githubusercontent.com/denilsonsa/prettyping/master/prettyping)
	chmod +x ~/bin/prettyping
}

function sizes {
	gdu -ad1 $1 | sort -nr | while read size fname
	do
		for unit in k M G T P E Z Y
		do
			if [ $size -lt 1024 ]
			then
				echo -e "${size}${unit}\t${fname}"
				break
			fi
			size=$((size/1024))
		done
	done
}
