#!/bin/bash -e

export PATH=$HOME/bin:/usr/local/bin:$PATH


export HISTFILESIZE=1000000000
export HISTSIZE=1000000000

setopt HIST_FIND_NO_DUPS
setopt INC_APPEND_HISTORY

alias less="less -N"
alias ls='ls -G --color'

export LC_ALL=en_US.UTF-8

alias getp='ps axu | grep -v grep | grep -i '
alias dev='cd ~/Documents/dev'

alias copy_thumbs='echo "![](https://cloud.githubusercontent.com/assets/1674699/4883145/3fd1640a-635f-11e4-87c5-902706e24727.png)![](https://cloud.githubusercontent.com/assets/1674699/4923944/d6e58bda-651e-11e4-82a0-90ce68a4357c.png)" | pbcopy'

alias speedtest='wget -O /dev/null http://speedtest.wdc01.softlayer.com/downloads/test100.zip'
alias ip='ifconfig | grep -e '\''inet [0-9]'\'' | grep -ve '\''inet 127'\'' | awk -F '\'' '\'' '\''{print $2; }'\'' | tr -d '\''\n'\'''
alias fastping='prettyping --nounicode -i 0.1'

function timestamp() {
  date -j -f '%Y-%m-%d %H:%M:%S' "$1" +%s
}

function install_prettyping() {
	(mkdir -p ~/bin && cd ~/bin && curl -O https://raw.githubusercontent.com/denilsonsa/prettyping/master/prettyping)
	chmod +x ~/bin/prettyping
}

function copy() { echo -n $@ | pbcopy; }

function run_in_all () {
	pattern=$1
	shift
	command="$@"
	if [ -z "$command" ] || [ -z "$pattern" ]
	then
		echo "usage: run_in_all <pattern> <command> [args..]"
		echo "where:"
		echo "  pattern = a name of a file/folder to look for"
		echo "  command = a command to run in each children folder when pattern is a readable file/folder"
	else
		for D in *
		do
			if [ -d "${D}" ] && [ -r "${D}/${pattern}" ]
			then
				echo "\n--> ${D}"
				(
					cd "${D}"
					eval $command
				)
			else
				echo "\n--> could not read ${D}/$pattern"
			fi
		done
	fi
}

function sizes {
	gdu -ad1 $1 | sort -nr | while read size fname
	do
		for unit in k M G T P E Z Y
		do
			if [ $size -lt 1024 ]
			then
				echo -e "${size}${unit}\t${fname}"
				break
			fi
			size=$((size/1024))
		done
	done
}
